
<a href='https://sites.google.com/site/jahangirypedram/'> <img src="logo.jpg" /></a>
___
## Pedram Jahangiry (Fall 2019)

# NumPy 

Topics to be covered:

1. Numpy arrays
2. Numpy indexing and extraction
3. Numpy operations



In [1]:
import numpy as np

##  1. NumPy Arrays

In [2]:
my_list = [0,1,2,3]
my_list

[0, 1, 2, 3]

In [3]:
np.array(my_list)

array([0, 1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Built in methods
# np.arange() :Return evenly spaced values within a given interval.
np.arange(0,4)

array([0, 1, 2, 3])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
# Zeros and ones : Generate arrays of zeros or ones
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# linspace : Return evenly spaced numbers over a specified interval. 
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
# eye: Creates identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# rand : create random samples from a uniform distribution
np.random.rand(5)

array([0.77486903, 0.85350139, 0.48430492, 0.21258824, 0.57196777])

In [18]:
np.random.rand(5,5)

array([[0.08438954, 0.6860236 , 0.19366086, 0.76239228, 0.90797059],
       [0.67131396, 0.10291199, 0.12634243, 0.96593048, 0.57157816],
       [0.89342121, 0.03772612, 0.63839609, 0.26079933, 0.98325   ],
       [0.12878027, 0.36541424, 0.50812992, 0.12899636, 0.83363412],
       [0.23096136, 0.95683225, 0.11691076, 0.73982021, 0.89454778]])

In [19]:
# randn : create random samples from standard normal distribution
np.random.randn(5)

array([-0.15553838,  1.5222392 , -0.55164113,  0.21721492, -0.81628973])

In [20]:
np.random.randn(5,5)

array([[-0.36390472,  1.13760358,  2.04332536, -0.24552415,  1.59046186],
       [ 0.14694068, -1.4578848 ,  0.37250081, -1.08024124, -0.43529669],
       [-1.03251824,  1.38260135, -1.59506057, -1.04578289, -1.41443573],
       [-1.22520922,  0.38486589, -0.44545674, -0.6604545 ,  0.43335946],
       [ 0.01840351,  0.36761893, -0.98905872, -0.29648749,  0.20133101]])

In [21]:
# randit(a,b) : create random sample of integers from a (including a) to b (excluding b) 
np.random.randint(1,5)

4

In [22]:
np.random.randint(1,5,20)

array([4, 3, 1, 2, 1, 4, 2, 3, 2, 1, 4, 2, 2, 2, 4, 1, 2, 2, 3, 3])

In [23]:
# seed is used to fix the random state.
np.random.seed(100)
np.random.randn(5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [24]:
np.random.seed(100)
np.random.randn(4)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604])

In [25]:
# array methods

my_array = np.arange(9)
my_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
# reshape
new_array = my_array.reshape(3,3)
new_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
new_array.shape

(3, 3)

In [28]:
new_array.dtype

dtype('int32')

In [29]:
type(new_array)

numpy.ndarray

In [30]:
my_array = np.append(my_array, [100,-100])
my_array

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,  100, -100])

In [31]:
my_array.max()

100

In [32]:
my_array.argmax()

9

In [33]:
my_array.min()

-100

In [34]:
my_array.argmin()

10

## 2. Numpy indexing and extraction

In [35]:
my_array

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,  100, -100])

In [36]:
# extraction is very similar to list extraction
my_array[9]

100

In [37]:
my_array[6:9]

array([6, 7, 8])

In [38]:
# With NumPy arrays, you can broadcast a single value across a larger set of values. This is not possible using lists. 

my_array[0:5]=100
my_array

array([ 100,  100,  100,  100,  100,    5,    6,    7,    8,  100, -100])

In [39]:
my_list = list(range(1,10))
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
my_list[0:5]

[1, 2, 3, 4, 5]

In [39]:
my_list[0:2]=100

TypeError: can only assign an iterable

In [40]:
my_list[0:2]=[100,100,100]
my_list

[100, 100, 100, 3, 4, 5, 6, 7, 8, 9]

In [41]:
# matrix: Note that matrix indexing in python is slightly different than R, Matlab or other programmings. 

my_matrix= np.arange(0,6).reshape(2,3)
my_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
# Format is matrix[row][col] or matrix[row,col]

# extracting the first row
my_matrix[0]

array([0, 1, 2])

In [43]:
# extracting the first column
my_matrix[:,0]

array([0, 3])

In [44]:
my_matrix[0][1] == my_matrix[0,1]

True

In [45]:
my_matrix[:2,1:]

array([[1, 2],
       [4, 5]])

Use google image to get help on "numpy array indexing" 


### Extracting with conditional selection


In [46]:
my_array

array([ 100,  100,  100,  100,  100,    5,    6,    7,    8,  100, -100])

In [47]:
my_array > 50

array([ True,  True,  True,  True,  True, False, False, False, False,
        True, False])

In [48]:
my_array[my_array>50]

array([100, 100, 100, 100, 100, 100])

In [49]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
my_matrix > 1

array([[False, False,  True],
       [ True,  True,  True]])

In [51]:
my_matrix[my_matrix > 1]

array([2, 3, 4, 5])

## 3. Numpy operations

In [52]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [53]:
arr + arr

array([0, 2, 4, 6, 8])

In [54]:
arr ** arr

array([  1,   1,   4,  27, 256], dtype=int32)

In [55]:
arr/arr

C:\Users\jahan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.])

In [56]:
1/arr

C:\Users\jahan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [57]:
# Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
# Exponential
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [59]:
# Natural Logarithm
np.log(arr)

C:\Users\jahan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [60]:
# summary statistics on arrays
arr

array([0, 1, 2, 3, 4])

In [61]:
arr.sum()

10

In [62]:
arr.mean()

2.0

In [63]:
arr.var()

2.0

In [64]:
arr.std()

1.4142135623730951

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [65]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
# axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns)
# again, note that the logic is different from R, Matlab or etc
my_matrix.sum(axis=0)

array([3, 5, 7])

In [67]:
my_matrix.sum(1)

array([ 3, 12])

In [68]:
my_matrix * my_matrix  # note that this is not a matrix multiplication

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [69]:
# To do a matrix multiplication use np.dot (equivalent to %*% in R)
np.dot(my_matrix,my_matrix.T)

array([[ 5, 14],
       [14, 50]])

In [70]:
# inverse of a matrix
A = np.array([[1,2],[3,4]]) 
A

array([[1, 2],
       [3, 4]])

In [71]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])